#!/bin/sh
 
### BEGIN INIT INFO
# Provides:		iptables
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:	 	0 1 6
# Short-description:	iptables
# Description: 		Firewall
### END INIT INFO
# chargement/déchargement d'iptables
 
case "$1" in
'start')
bash /etc/init.d/rules_firewall
#/sbin/iptables-restore < /etc/config_parefeu
RETVAL=$?
;;
'stop')
#/sbin/iptables-save > /etc/config_parefeu
echo -e "#####################################################################################################"
echo -e
echo -e "stop le parefeu pendant que la machine tourne"
echo -e  "a peut être une faille de sécurite si on l'exécute lors de l'extinction avant l'arrêt des interfaces"
echo -e "pense à refaire un start après sinon la sauvegarde se fera automatiquement à l'extinction"
echo -e
echo -e "#####################################################################################################"
/sbin/iptables -t filter -F
/sbin/iptables -t nat -F
/sbin/iptables -t mangle -F
/sbin/iptables -t raw -F
/sbin/iptables -t filter -P INPUT ACCEPT
/sbin/iptables -t filter -P OUTPUT ACCEPT
/sbin/iptables -t filter -P FORWARD ACCEPT
/sbin/iptables -t nat -P PREROUTING ACCEPT
/sbin/iptables -t nat -P POSTROUTING ACCEPT
/sbin/iptables -t nat -P OUTPUT ACCEPT
/sbin/iptables -t mangle -P PREROUTING ACCEPT
/sbin/iptables -t mangle -P OUTPUT ACCEPT
/sbin/iptables -t mangle -P POSTROUTING ACCEPT
/sbin/iptables -t mangle -P FORWARD ACCEPT
/sbin/iptables -t mangle -P INPUT ACCEPT
/sbin/iptables -t raw -P OUTPUT ACCEPT
/sbin/iptables -t raw -P PREROUTING ACCEPT
RETVAL=$?
;;
'restart')
$0 stop && $0 start
RETVAL=$?
;;
*)
echo "Usage: $0 { start | stop | restart }"
RETVAL=1
;;
esac
exit $RETVAL
